### PR TITLE
Reduce garbage when sending and receiving data in synchronous tls channel

### PR DESCRIPTION
**Pull request by motocodeltd**
Thank you for writing this - we're finding it very useful. 

We're having an issue while using the synchronous channel. That is, every time a read or a write occurs, objects (the ByteBufferSet) are constructed. Those objects are not reused and then immediately discarded, leading to frequent memory allocation, dereferencing and eventually garbage collection.

We're using tsl-channel in a high throughput low latency application and we really care about garbage generation, so that we can avoid GC pauses. This PR does the following:

- Makes ByteBufferSet an interface
- Encapsulates reading and writing inside implementations of the interface (thus not exposing offsets, lengths and arrays)
- Renames the existing implementation to ImmutableByteBufferSet
- Introduces two other implementations: MutableByteBufferSet and MutableSingleByteBufferSet
- Uses those in ServerTlsChannel and ClientTlsChannel, thus getting rid of the allocation on send / receive
- Makes the Wrap/UnwrapResults mutable and uses those in ClientTlsChannel

This reduces allocation substantially during steady state (i.e. when handshake is established).

Thanks again!

Stefanos

### CODE REVIEW

**Comment by marianobarrios** [comment]
Hi Stefanos,

Thanks for the contribution. I generally think that the idea just makes sense.

I just about to merge it, when I realized that there may be a concurrency problem. Note that the locks for reading and writing are inside `TlsChannelImpl`, not the user-visible `ClientTlsChannel` and `ServerTlsChannel`. However, these are the holders of the mutable buffers, that get modified before trying the lock. So my assumption is that concurrent operations of the same type, would not just lock and wait, but corrupt each other buffers. Makes sense? I guess that pushing the mutable buffers into `TlsChannelImpl` can just fix this...

**Comment by motocodeltd** [comment]
Hi Mariano,

That's right - thanks for pointing that out. We don't use concurrent access so we haven't come accross this issue. I will move the buffers inside the impl class. I will also submit another PR that makes locking optional (will default it to be present) for clients that don't need to have the locking overhead.

**Comment by motocodeltd** [comment]
This has now been done, wrapping happens after the lock is aquired. If this is merged, I will submit a separate PR that makes the locking optional.

**Comment by marianobarrios** [comment]
Thanks, I will take a look shortly. BTW, I added a new test that would have caught the previous concurrency problem. It's already on master, so you may have to rebase master (or merge) to see if it passes here too (as a double precaution).

**Comment by marianobarrios** [comment]
I think that the same change is pending in ServerTlsChannel.

**Comment by motocodeltd** [comment]
Hi Mariano - I've rebased my branch and the test now passes. We're not using the server side tls-channel and I wasn't sure if this change would be accepted, so I will port it server side too and update.

**Comment by marianobarrios** [comment]
I see that the same change as in the client could not be applied, as the server is more complex. The problem is that the last commit introduces double locking (at the server and at the internal class). I created a pull request to _your_ branch that addresses this.

**Comment by motocodeltd** [comment]
Hi - I've merged your PR which has updated this PR. Thanks

**Comment by marianobarrios** [comment]
I gave a second look and realized that the re-use of WrapResult and UnwrapResult are not thread safe (please, correct me if I am wrong). The reason is that a concurrent read and write could be both doing unwrap or wrap...

In any case, I realized that a relatively simple refactoring can get rid of those objects altogether (and also of some garbage-generating Optional). It's in master, what do you think?

Additionally, I created a garbage-measuring test, in order to quantify the garbage generated.

**Comment by motocodeltd** [comment]
I don't think that's the case as WrapResult is only called either as part of a write (protected by the write lock), as part of handshake (protected again by the write lock), or shutdown (protected by the writelock).

Unwrap result is similarly protected by the readLock. There's no concurrent access that I can see to those wrappers that's not protected by locks. How would you like to proceed?

**Comment by motocodeltd** [comment]
also worth pointing out that we have about another 4-5 pending PRs that are based on this on that reduce lots of garbage (including the optionals), and make various improvements around handshakes and the like.

**Comment by marianobarrios** [comment]
Regarding concurrency, I think you are correct; sorry for introducing the confusion. 

I am just worried about increasing complexity. I pushed my changes to master because I found a way of removing WrapResult, UnwrapResult, and all the Optionals _while at the same time simplifying the code_ (net -16 LOC). Please take a look, I think it's very reasonable.

I also introduced a test, that uses the new no-op GC (-XX:+UseEpsilonGC) in order to measure GC pressure (that collector does not free anything, so it's useful for these measures). I would really like to weigh increases in LOC and complexity against measurable improvements in allocation.

In the current test, transmitting 1 MB twice, allocated 70 MB in total. I am not claiming that the test is ideal, as the test itself may be allocating too much memory. I am of course open to improving it. But the bottom line is IMO we have to justify the increases in complexity. It could be that SSLEngine itself allocated the bulk of it and that any improve we make in the TlsChannel would not be significant. It could also be the opposite, but my point is that I think measuring is important.

**Pull request closed without merging**
