### PR TITLE
Fix IndexOutOfBoundsException in TlsChannelImpl

### PR DESCRIPTION
**Pull request by blachris**
This change fixes an IndexOutOfBoundsException that is thrown in my use case in the first handshake in the TlsChannelImpl: 

java.lang.IndexOutOfBoundsException: offset: 0, length: 0 (expected: offset <= offset + length <= srcs.length (0))

	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.wrap(ReferenceCountedOpenSslEngine.java:688)
	at tlschannel.impl.TlsChannelImpl.callEngineWrap(TlsChannelImpl.java:388)
	at tlschannel.impl.TlsChannelImpl.wrapLoop(TlsChannelImpl.java:370)
	at tlschannel.impl.TlsChannelImpl.handshakeLoop(TlsChannelImpl.java:539)
	at tlschannel.impl.TlsChannelImpl.handshake(TlsChannelImpl.java:519)
	at tlschannel.impl.TlsChannelImpl.doHandshake(TlsChannelImpl.java:494)
	at tlschannel.impl.TlsChannelImpl.handshake(TlsChannelImpl.java:480)
	at tlschannel.ClientTlsChannel.handshake(ClientTlsChannel.java:184)

### CODE REVIEW

**Comment by marianobarrios** [comment]
Hi Christopher,

I see that CI failed (which uses the standard SSLChannel). In order to not do this blindly, would you have code (or test function) that actually uses the Netty OpenSSL wrapper? That way I could reproduce the problem...

Thanks!

**Comment by chris-blacker** [comment]
Thanks for having a look @marianobarrios 
I added a java unit test. It should fail without this fix with the above exception.

**Comment by marianobarrios** [comment]
I took your branch, could not merge it directly because there was a problem with the tests (Gradle was running only the new tests). So I actually implemented the change directly. It's now on master are all tests passing (including the new one).

**Comment by blachris** [comment]
Thank you very much, that is fine. Please consider publishing a new artifact that includes the fix to maven central eventually. I think the 0.3.2 does not include it yet.

**Pull request closed without merging**
