### PR TITLE
Feature/android_ci

### PR DESCRIPTION
**Pull request by Erhannis**
Ok, so I think I've got this working.  I copied in a test of direct buffer deallocation, run on Android, as well as a test of a blocking client and server exchanging messages, which I figure should test a fair chunk of the system.  (Note though - the deallocation code has become sorta best-effort; it tries to get as many cleaner methods as it can, and then runs through them until one doesn't throw OR it runs out, and returns normally regardless.)  Github CI was sorta weird about certain things (like gradle throwing out-of-memory errors), so I've set the Java tests to run without the Android stuff being visible, and the Android tests to run alone (but depending on the Java stuff).  The Java tests and the Android tests now all complete successfully.  The Android tests run on api levels 19, 23, and 29.

### CODE REVIEW

**Comment by marianobarrios** [comment]
Thanks a lot for all this effort! I almost could not believe seeing all the tests green :-).

I would love to merge this. However, I would prefer to try to minimize changes as much as possible. 

The first idea I have is: I see that some "java8." imports are needed because of old Android versions. However, Android 29 seems to have LongAdder, for example. Could not we first build for the newest version possible, and then afterwards add older versions?

Another question I have is about the files in `android/src/androidTest/java`. Cannot they just be in `src/test/java`: I don't see any reason why those tests could not be run in java...

**Comment by marianobarrios** [comment]
Thanks a lot for all this effort! I almost could not believe seeing all the tests green :-).

I would love to merge this. However, I would prefer to try to minimize changes as much as possible. 

The first idea I have is: I see that some "java8." imports are needed because of old Android versions. However, Android 29 seems to have LongAdder, for example. Could not we first build for the newest version possible, and then afterwards add older versions?

Another question I have is about the files in `android/src/androidTest/java`. Cannot they just be in `src/test/java`: I don't see any reason why those tests could not be run in java...

**Comment by Erhannis** [comment]
`Could not we first build for the newest version possible, and then afterwards add older versions?`  I'm not sure what you mean - just, make code that works for newer Android first, and then modify it to also work with older Android?  I don't see how that will give us a better result - usually incrementally changing things like that gives a _messier_ final product; it's generally cleaner to make changes all at once, if you know what needs changed.  Did you mean something else?

Re: `android/src/androidTest/java` vs `src/test/java` - if we do the latter, the tests are run on the plain computer, not an Android device.  The point of my changes was to run tests _on an Android device_ (or an emulator, at least), because that's where things were failing.  The tests I'm running in `androidTest` are more-or-less also covered by the tests running in the normal `java` tests, but I put them in `androidTest` to be more sure the code actually works on Android.

**Comment by marianobarrios** [comment]
> make code that works for newer Android first, and then modify it to also work with older Android? I don't see how that will give us a better result - usually incrementally changing things like that gives a messier final product; it's generally cleaner to make changes all at once, if you know what needs changed. Did you mean something else?
Yes, I mean that. The reality is that this changeset contains too many changes to be easily understood. Making incremental changes that are, individually, easy to understand and so bring a reasonably high confidence that they are correct ("obviously no errors", paraphrasing Tony Hoare) is just how complex software is made. On top of that, please keep in mind that this library is used in production and already quite stable, being somewhat conservative just makes sense.

Android and Java are not the same thing; they are just source-compatible to some degree, that's it. Cross-building between them is rare in the community, I think for this reason. To be honest, I am not sure if that will be achievable here within reasonable complexity. But I am willing to give it a try, as this library has almost no dependencies and is low-level enough.

But we need a plan for this. My proposal is:
- If Scala is a problem, get rid of it, at least partially. The Scala tests are in retrospect a mistake IMO. We can re-write some of them for the sake of the Android build. We can do this as a first step without any Android-specific change at all.
- This library targets Java 8, which is relatively old. Targeting a new-enough version of Android will minimize (eliminate?) source changes.

I am sure you will have more ideas. We can do this together if you want.

**Pull request closed without merging**
