### PR TITLE
Feature/android support

### PR DESCRIPTION
**Pull request by Erhannis**
I discovered that tls-channel doesn't work on Android - at least, I had some problems.  I've patched it to work - are these changes acceptable for pulling back into the main repo?

I added a dependency on streamsupport, for two `atomic` classes not present on some versions of Android.  We could probably just copy in out the two classes used from it, instead of the dependency.

I also added a few backup mechanisms in DirectBufferDeallocator - I've tried several versions of Android, and encountered several variations on the internal cleanup code - sometimes classes are missing, sometimes fields, etc.  The changes I made appear to work with the three versions of Android I've tested - 6.0.1, and maybe 10 or 11, I think; I'm not sure what version the other was.

Let me know if anything needs to be changed.

### CODE REVIEW

**Comment by marianobarrios** [comment]
Hi @Erhannis, thanks for the pull request. I have never developed for Android, so this is a somewhat new world for me. I find this feature (so to speak) interesting and I am open to including it. However, I would have a question: can we somehow test this in continuous integration (GitHub Actions)? Otherwise I would be merging blindly, with no practical way of being sure that we actually _maintain_ Android support in the future. If we do this I would mention the support in the READ-ME, but that implies a commitment to keep it working...

**Comment by Erhannis** [comment]
I'm currently trying to see if I can get that working; I'll let you know if I manage it.

I mentioned possibly copying the two relevant classes in, rather than a dependency, but it looks like they reference classes that reference classes, etc., and some of them are GPLv2, so that's probably not a viable option.

**Comment by Erhannis** [comment]
I'm very slowly working my way through this - is there a particular reason you do the tests in scala?  It's a very complicating factor, trying to get them to run also on Android.

One possible alternative to what I've been trying to do is to write a few tests specifically for Android, covering the changes I made, and maybe a few main uses of the library, and then assume that if it runs in Java and these couple tests run in Android that probably the rest of it's fine, as well.  What are your thoughts?  I've been [having trouble](https://stackoverflow.com/q/70980178/513038) finding out [how to run java/scala tests](https://stackoverflow.com/q/71154126/513038) again [on Android itself](https://stackoverflow.com/q/71195281/513038).

**Comment by marianobarrios** [comment]
> is there a particular reason you do the tests in scala?
No. Just conciseness, but that was probably a good reason when this project started almost 10 years ago. With the newer Java versions tests could be done in that language more conveniently (even if keeping the main code at Java 8).

> write a few tests specifically for Android, covering the changes I made, and maybe a few main uses of the library, and then assume that if it runs in Java and these couple tests run in Android that probably the rest of it's fine
Yes, I think this is fine. In the end, if this library keeps being relevant for more time, those Scala tests should be rewritten in Java, some day.

**Comment by Erhannis** [comment]
Ok, I think I got it working: #46

**Pull request closed without merging**
